name: flat

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Decrypt
        run: ./.github/scripts/decrypt_secret.sh
        env:
          KEYSTORE_SECRET_PASSPHRASE: ${{ secrets.KEYSTORE_SECRET_PASSPHRASE }}
          GRADLE_SECRET_PASSPHRASE: ${{ secrets.GRADLE_SECRET_PASSPHRASE }}

      - name: Config
        run: ./.github/scripts/project_config.sh
        env:
          ALIYUN_LOG_DEV_AK: ${{ secrets.ALIYUN_LOG_DEV_AK }}
          ALIYUN_LOG_DEV_SK: ${{ secrets.ALIYUN_LOG_DEV_SK }}
          ALIYUN_LOG_PROD_AK: ${{ secrets.ALIYUN_LOG_PROD_AK }}
          ALIYUN_LOG_PROD_SK: ${{ secrets.ALIYUN_LOG_PROD_SK }}

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-${{ hashFiles('checksum.txt') }}

      - name: Build project
        run: ./gradlew assembleRelease --stacktrace

      - name: Archive reports for failed build
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: build-reports
          path: '*/build/reports/'

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: flat-artifact
          path: app/build/outputs/apk/**/release/*.apk
